start stepper – Target audience
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #105
Opened 2023-03-26 13:06 UTC by Alexandr-mas

![image](https://user-images.githubusercontent.com/84984785/227777500-02140bb2-596c-4277-8b8c-3dffac28cb45.png)
step looks like this
![image](https://user-images.githubusercontent.com/84984785/227777555-2d80cbe0-ec3e-4531-8d11-1dd081646560.png)
Now, with this commit, this step is not called anywhere in the way that more will be created and then added to one array.

2023-03-26 19:40 UTC, andanf-e requested changes

2023-03-26 19:40 UTC, andanf-e commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +import { SelectTarget } from '../../select-target/select.js';
Should use default select with enhanced stuff
```suggestion
import { Select } from '~/libs/components/components.js';
```

2023-03-26 19:40 UTC, andanf-e commented on frontend/src/libs/components/select-target/styles.ts
custom styled checkbox should be added into custom options component for multiselect

2023-03-28 13:34 UTC, Alyona-Pisotska requested changes

2023-03-28 13:34 UTC, Alyona-Pisotska commented on frontend/src/libs/components/select-target/styles.ts
> +import ceckIcon from 'src/assets/img/icons/choice.svg';
grammatical error?

2023-03-28 13:34 UTC, Alyona-Pisotska commented on frontend/src/libs/components/stepper/step-target/style.module.scss
> +  font-family: Roboto, sans-serif;
You don`t need to add font-family - it is global

2023-03-28 13:34 UTC, Alyona-Pisotska commented on frontend/src/libs/components/stepper/step-target/style.module.scss
> +  font-family: Roboto, sans-serif;
same

2023-03-29 14:45 UTC, Alexandr-mas commented
![image](https://user-images.githubusercontent.com/84984785/228576447-bc27ce13-4a5d-404c-be26-a0ca44a530a0.png)
step look like this

2023-03-30 11:31 UTC, what1s1ove requested changes

2023-03-30 11:31 UTC, what1s1ove commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +import PropTypes from 'prop-types';
```suggestion
```

2023-03-30 11:31 UTC, what1s1ove commented on frontend/src/libs/components/stepper/step-target/style.module.scss
> +input[type="checkbox"]:checked::before {
use classes
but better to use ReactSelect style api

2023-03-30 11:31 UTC, what1s1ove commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +};
```suggestion
```
use typescript instead

2023-03-30 16:11 UTC, bohdan-degtiar requested changes

2023-03-30 16:11 UTC, bohdan-degtiar commented on frontend/src/libs/components/stepper/step-target/style.module.scss
> +  background-color: #343434;
move `#343434` to variable

2023-03-30 16:11 UTC, bohdan-degtiar commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +import { useForm } from 'react-hook-form';
use `useAppForm`

2023-03-30 16:11 UTC, bohdan-degtiar commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +        }}
Don`t add customComponents this way.

2023-03-30 16:11 UTC, bohdan-degtiar commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +        ]}
Move to separate variable.

2023-03-30 16:13 UTC, bohdan-degtiar commented on frontend/src/libs/components/stepper/step-target/stepper-target.tsx
> +        isMulti={true}
Boolean property can set this way
```suggestion
        isMulti
```

2023-04-03 07:26 UTC, what1s1ove commented
duplicate of https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland/pull/172

2023-04-03 07:26 UTC, what1s1ove commented
duplicate of https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland/pull/172

2023-04-03 07:26 UTC, closed without merging