sl-114: Site page
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #123
Opened 2023-03-29 14:40 UTC by dimapopovych

![Screenshot 2023-03-29 173451](https://user-images.githubusercontent.com/100519494/228573562-66d61217-3f77-48ba-9157-eca8d8819f63.png)
![Screenshot 2023-03-29 173342](https://user-images.githubusercontent.com/100519494/228573566-5640e918-b9ea-4304-9912-578ecd2a8726.png)
There is a little problem)

2023-03-29 14:47 UTC, dimapopovych commented on frontend/src/packages/sections/sections-api.ts
> +        hasAuth: true,
```suggestion
        hasAuth: false,
```
If route will be public

2023-03-29 14:47 UTC, dimapopovych commented on frontend/src/pages/site/site.tsx
> +        case 'header': {
SectionType.HEADER

2023-03-29 14:47 UTC, dimapopovych commented on frontend/src/slices/sections/actions.ts
> +import { type SectionGetAllItemResponseDto } from 'shared/build/index.js';
import

2023-03-29 15:16 UTC, dimapopovych commented
![image](https://user-images.githubusercontent.com/100519494/228585932-92455649-de0a-41fa-8368-1bb1b3f4b615.png)

2023-03-30 09:21 UTC, what1s1ove requested changes

2023-03-30 09:21 UTC, what1s1ove commented on frontend/src/packages/sections/sections-api.ts
> +      this.getFullEndpoint(SitesApiPath.SECTIONS_BY_SITE, {
```suggestion
      this.getFullEndpoint(SitesApiPath.$SITE_ID_SECTIONS, {
```

2023-03-30 09:28 UTC, what1s1ove commented on frontend/src/packages/sections/sections-api.ts
> +      this.getFullEndpoint(SitesApiPath.SECTIONS_BY_SITE, {
all dynamic parameters should start from `$`

2023-03-30 09:48 UTC, what1s1ove approved these changes

2023-03-30 09:48 UTC, merged