sl-71: target audience
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #172
Opened 2023-04-03 07:07 UTC by Alexandr-mas

…ct, made a multiselect, changed the visual styles

2023-04-03 07:28 UTC, jaroslawtt commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
> +} from 'shared/build';
Should it actually be imported exact from shared/build?

2023-04-03 07:30 UTC, jaroslawtt requested changes

2023-04-03 07:30 UTC, jaroslawtt commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
> +import { type ReactNode } from 'react';
Can use React.ReactNode 
```suggestion

```

2023-04-03 08:57 UTC, Alexandr-mas commented
![image](https://user-images.githubusercontent.com/84984785/229461381-a39049e7-9920-415f-b4b7-0dff2a1722ed.png)
this is with validation
![image](https://user-images.githubusercontent.com/84984785/229461552-28b4fc84-0fd8-4327-8ba6-ccb091421c7c.png)
it's a multiselect

2023-04-03 09:15 UTC, what1s1ove requested changes

2023-04-03 09:15 UTC, what1s1ove commented on shared/src/packages/sites/libs/validation-schemas/site-create-step-target.validation-schema.ts
> +    .array()
should be an array of strings

2023-04-03 09:15 UTC, what1s1ove commented on frontend/src/pages/start/start.tsx
> +import { TargetAudience } from './libs/components/target-audience-form/target-audience-form.js';
```suggestion
import { TargetAudienceForm } from './libs/components/target-audience-form/target-audience-form.js';
```
concat the imports

2023-04-03 09:15 UTC, what1s1ove commented on shared/src/packages/sites/libs/validation-schemas/site-create-step-target.validation-schema.ts
> +    .min(1)
add validation rule for all rules

2023-04-04 17:33 UTC, andanf-e commented on frontend/src/libs/components/select/select.tsx
> +  customComponents?: object;
First of all custom components in react-select may be typed,, and the second - you should provide customComponents as outer props - but just specify and pass needed ones if it's multiselect

2023-04-04 17:33 UTC, andanf-e commented on shared/src/packages/sites/libs/types/site-create-request-dto.type.ts
> +  targetAudience: { label: string; value: string }[];
But it should be array of strings

2023-04-04 17:33 UTC, andanf-e commented on shared/src/packages/sites/libs/types/site-create-response-dto.type.ts
> +  targetAudience: { label: string; value: string }[];
Same about array of strings

2023-04-04 17:33 UTC, andanf-e commented on shared/src/packages/sites/libs/enums/site-validation-message.enum.ts
> +  SITE_TARGET_WRONG: 'Invalid field',
What field is required and what is invalid -- you have specific keys and abstract messages

2023-04-04 17:33 UTC, andanf-e commented on shared/src/packages/sites/libs/types/site-create-step-target.type.ts
> +  targetAudience: { label: string; value: string }[];
```suggestion
  targetAudience: string[];
```

2023-04-04 17:33 UTC, andanf-e commented on shared/src/packages/sites/libs/types/site-get-all-item-response-dto.type.ts
> +  targetAudience: { label: string; value: string }[];
```suggestion
  targetAudience: string[];
```

2023-04-05 17:55 UTC, Izdormu commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
>            label="Next"
Change label name to "Go next"

2023-04-05 18:06 UTC, andanf-e commented on backend/src/packages/sites/site.service.ts
> +        targetAudience: [],
It's not a part of sites entity

2023-04-05 18:06 UTC, andanf-e commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
Pay attention on warns about never used stuff

2023-04-06 08:36 UTC, what1s1ove requested changes

2023-04-06 08:36 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
> +          isMulti
should not a multiple select (according the documentation)

2023-04-06 10:46 UTC, Alexandr-mas commented
![image](https://user-images.githubusercontent.com/84984785/230354921-f693212f-af01-4223-b6dc-e62ced0786c9.png)

2023-04-06 10:46 UTC, jaroslawtt approved these changes

2023-04-06 11:12 UTC, what1s1ove requested changes

2023-04-06 11:12 UTC, what1s1ove commented on backend/src/packages/sites/site.service.ts
> +    const EXAMPLE_TARGET = 'young-adult';
use enum values here

2023-04-06 12:04 UTC, Alyona-Pisotska requested changes

2023-04-06 12:04 UTC, Alyona-Pisotska commented on backend/src/packages/sites/site.service.ts
> +import { SiteTargetType } from 'shared/build/index.js';
fix import

2023-04-06 12:04 UTC, Alyona-Pisotska commented on frontend/src/pages/start/libs/components/target-audience-form/style.module.scss
> +  border-color: black;
use a variable from variables.scss

2023-04-06 12:04 UTC, Alyona-Pisotska commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
> +      <h2 className={getValidClassNames(style['title'])}>
You don't need `getValidClassNames ` there

2023-04-06 12:04 UTC, Alyona-Pisotska commented on frontend/src/pages/start/libs/components/target-audience-form/target-audience-form.tsx
> +      <div className={getValidClassNames(style['subtitle'])}>
same

2023-04-06 13:26 UTC, what1s1ove approved these changes

2023-04-06 13:26 UTC, merged