sl-154: The error message contain extra word on the Change password page
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #183
Opened 2023-04-03 16:06 UTC by Izdormu

![pass text](https://user-images.githubusercontent.com/49407959/229565580-37ef1099-27d3-4a14-808c-1b131ded58b0.png)

2023-04-03 17:56 UTC, andanf-e approved these changes

2023-04-04 14:28 UTC, what1s1ove commented on .eslintrc.yml
> +      - commitlint.config.ts
shouldn't be changed

2023-04-04 14:28 UTC, what1s1ove commented on package-lock.json
> -    "node_modules/classnames": {
shouldn't be changed

2023-04-05 07:06 UTC, what1s1ove requested changes

2023-04-05 07:06 UTC, what1s1ove commented on .eslintrc.yml
> +      - commitlint.config.ts
isn't resolved

2023-04-05 18:02 UTC, andanf-e approved these changes

2023-04-06 07:26 UTC, merged