sl-173: Start stepper tone of voice
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #199
Opened 2023-04-05 10:18 UTC by jaroslawtt

![image](https://user-images.githubusercontent.com/87016333/230052109-11efb501-b2c5-460d-942a-ac45e257ecb1.png)
with icon
![image](https://user-images.githubusercontent.com/87016333/230052430-5972eb87-d6b6-4b15-9b8f-9f01a85f0ac6.png)

2023-04-05 13:01 UTC, what1s1ove requested changes

2023-04-05 13:01 UTC, what1s1ove commented on frontend/src/packages/sites/libs/enums/enums.ts
> +export { SiteToneType } from 'shared/build/index.js';
merge imports

2023-04-05 13:01 UTC, what1s1ove commented on shared/src/packages/sites/libs/validation-schemas/site-create.validation-schema.ts
> +  tone: joi.string().required(),
should be only values from an enum

2023-04-05 13:01 UTC, what1s1ove commented on shared/tsconfig.json
> +    "skipLibCheck": true
move it

2023-04-05 13:01 UTC, what1s1ove commented on shared/src/packages/sites/libs/validation-schemas/site-create-step-tone.validation-schema.ts
> +const siteCreateStepTone = joi.object<SiteCreateStepTone>({
```suggestion
const siteCreateStepTone = joi.object<SiteCreateStepTone, true>({
```

2023-04-05 13:01 UTC, what1s1ove commented on shared/src/packages/sites/libs/types/site-create-request-dto.type.ts
> +import { type ValueOf } from '~/libs/types/value-of.type';
import

2023-04-05 13:01 UTC, what1s1ove commented on shared/src/packages/sites/libs/types/site-create-request-dto.type.ts
> +import { type SiteToneType } from '~/packages/sites/libs/enums/enums.js';
import
```suggestion
import { type SiteToneType } from '~/packages/sites/sites.js';
```

2023-04-05 13:01 UTC, what1s1ove commented on frontend/src/pages/start/libs/constants.ts
> +import { SiteToneType } from '~/packages/sites/libs/enums/enums.js';
```suggestion
import { SiteToneType } from '~/packages/sites/sites.js';
```

2023-04-05 13:01 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/voice-tone-form.tsx
> +import { siteCreateStepToneValidationSchema } from '~/packages/sites/libs/validation-schemas/validation-schemas.js';
```suggestion
import { siteCreateStepToneValidationSchema } from '~/packages/sites/libs/validation-schemas/validation-schemas.js';
```
```suggestion
import { siteCreateStepToneValidationSchema } from '~/packages/sites/sites.js';
```

2023-04-05 13:01 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/voice-tone-form.tsx
> +import { type SiteCreateStepTone } from '~/packages/sites/libs/types/types.js';
same

2023-04-05 13:01 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/voice-tone-form.tsx
> +    mode: 'onSubmit',
```suggestion
```
it by default

2023-04-05 13:01 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/libs/constants.ts
> +];
```suggestion
const options: SelectOption<string | number>[] = Object.values(SiteToneType).map((it) => ({
  value: it,
  label: siteToneTypeToReadable[it]
}))
```

2023-04-05 17:27 UTC, andanf-e commented on frontend/src/pages/start/libs/components/voice-tone-form/libs/constants.ts
> +const OPTIONS: SelectOption<string | number>[] = Object.values(
Looks like it's not `string | number` - you actually know the type of values passed (`SiteToneType` vals)

2023-04-06 07:40 UTC, what1s1ove requested changes

2023-04-06 07:40 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/libs/constants.ts
> +const defaultPayload: SiteCreateStepTone = {
```suggestion
const DEFAULT_FORM_PAYLOAD: SiteCreateStepTone = {
```

2023-04-06 07:40 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/libs/site-tone-type-to-readable.enum.ts
> +const SiteToneTypeToReadable = {
```suggestion
const siteToneTypeToReadable = {
```

2023-04-06 07:40 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/libs/site-tone-type-to-readable.enum.ts
> +import { SiteToneType } from '~/packages/sites/libs/enums/enums.js';
move to 
`frontend/src/pages/start/libs/components/voice-tone-form/libs/maps/site-tone-type-to-readable.map.ts`

2023-04-06 07:40 UTC, what1s1ove commented on frontend/src/pages/start/libs/components/voice-tone-form/libs/constants.ts
> +import { SiteToneTypeToReadable } from './site-tone-type-to-readable.enum.js';
```suggestion
import { SiteToneTypeToReadable } from './maps/maps.js';
```

2023-04-06 08:30 UTC, what1s1ove approved these changes

2023-04-06 08:30 UTC, merged