sl-100: Stripe integration
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #202
Opened 2023-04-05 14:53 UTC by dimapopovych

![image](https://user-images.githubusercontent.com/100519494/230118541-bf24e5c2-7077-4775-ad05-67596b2e4ace.png)
![image](https://user-images.githubusercontent.com/100519494/230118682-e429d6bf-f58e-4386-a8a9-34792bf21b8c.png)
Failed to implement this with stripe subscriptions, so decided to do this via charges

2023-04-07 15:31 UTC, andanf-e approved these changes

2023-04-07 15:56 UTC, what1s1ove requested changes
do not forget to change schema in readme.md

2023-04-07 15:56 UTC, what1s1ove commented on backend/src/db/migrations/20230405083951_add_subscription_table.ts
> +  SUBSCRIPTION_END: 'subscription_end',
```suggestion
  SUBSCRIPTION_END: 'end_date',
```

2023-04-07 15:56 UTC, what1s1ove commented on backend/src/packages/users/user.entity.ts
> +  private 'subscriptionEnd': string | null;
```suggestion
  private 'subscriptionEndDate': string | null;
```

2023-04-07 15:56 UTC, what1s1ove commented on frontend/.env.example
> +VITE_APP_STRIPE_PUBLIC_KEY=[stripe-public-key]
```suggestion
VITE_APP_STRIPE_PUBLIC_KEY=stripe-public-key
```

2023-04-07 15:56 UTC, what1s1ove commented on frontend/src/libs/components/checkout/styles.scss
> +/* stylelint-disable selector-class-pattern */
add overrides in `stylelint` config for this

2023-04-07 15:56 UTC, what1s1ove commented on frontend/src/libs/components/checkout/checkout.tsx
> +      amount={price * 100}
add constant

2023-04-08 07:35 UTC, what1s1ove approved these changes

2023-04-08 07:35 UTC, merged