sl-225: Type select field
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #240
Opened 2023-04-08 11:15 UTC by jaroslawtt

![image](https://user-images.githubusercontent.com/87016333/230718189-7097a4c9-0036-40ec-9d0c-e77d01c88134.png)

2023-04-08 14:50 UTC, what1s1ove requested changes

2023-04-08 14:50 UTC, what1s1ove commented on frontend/src/libs/components/select/select.tsx
> +  label?: string;
```suggestion
  label: string;
```
label should be always

2023-04-09 05:38 UTC, andanf-e approved these changes

2023-04-09 07:54 UTC, what1s1ove approved these changes

2023-04-09 07:54 UTC, merged