sl-165: Add preview for site
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #241
Opened 2023-04-08 12:42 UTC by jaroslawtt

https://user-images.githubusercontent.com/87016333/230721644-190f6f2e-77b2-4611-b441-217eb7f9eb0d.mp4

2023-04-08 14:55 UTC, what1s1ove requested changes
1. make all aria clickable (using pos: relative for parent and pos: absolute for link:before
2. remove this 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/42296182/230727931-a4838190-5488-4873-ad38-9d4d8567458a.png">

2023-04-09 09:10 UTC, jaroslawtt commented
> 1. make all aria clickable (using pos: relative for parent and pos: absolute for link:before
> 2. remove this
> 
> <img alt="image" width="289" src="https://user-images.githubusercontent.com/42296182/230727931-a4838190-5488-4873-ad38-9d4d8567458a.png">

Why I can't just wrapp it with link component?

2023-04-09 11:04 UTC, jaroslawtt commented
https://user-images.githubusercontent.com/87016333/230768854-c608e175-e743-4b79-93f0-8db213c564a2.mp4

2023-04-09 13:04 UTC, what1s1ove approved these changes

2023-04-09 13:04 UTC, merged