sl-242: Added getting project name and render it
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #247
Opened 2023-04-09 16:34 UTC by jaroslawtt

![image](https://user-images.githubusercontent.com/87016333/230784855-2717b6b7-d0de-4559-9334-4b816cf77755.png)
project: 
![image](https://user-images.githubusercontent.com/87016333/230784865-ffba5dea-2021-48b2-8de2-25ee7b9fa75e.png)
if no projects in store: 
![image](https://user-images.githubusercontent.com/87016333/230784879-264f44f7-f9e7-4f73-97e9-cfe22f414523.png)

2023-04-09 16:42 UTC, what1s1ove requested changes

2023-04-09 16:42 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +  const projectName =
add a new property to the reducer. it should be a current project

2023-04-10 07:21 UTC, what1s1ove requested changes

2023-04-10 07:21 UTC, what1s1ove commented on frontend/src/libs/components/link/link.tsx
> +  onClick?: () => void;
```suggestion
```
avoid onClick on link

2023-04-10 07:21 UTC, what1s1ove commented on frontend/src/pages/my-projects/components/project-card/project-card.tsx
> +          onClick={handleChooseProject}
```suggestion
```
what if use will open sites page directly by the link? without any clicks

2023-04-10 07:21 UTC, what1s1ove commented on frontend/src/slices/projects/projects.slice.ts
> +  currentProject: null,
you need to load at all the time when user opens the site page
LOAD. not just take from reducer

2023-04-10 15:32 UTC, what1s1ove requested changes

2023-04-10 15:32 UTC, what1s1ove commented on frontend/src/packages/projects/projects-api.ts
> +  public async getProject(parameters: {
```suggestion
  public async getById(parameters: {
```

2023-04-10 15:32 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +          void dispatch(
call two action in parallel

2023-04-10 15:32 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +  const projectName = project?.name ?? 'My sites';
```suggestion
```

2023-04-10 15:32 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +              <h2>{projectName}</h2>
```suggestion
              <h2>{project.name}</h2>
```
project should be always be here. use data status to show a loader

2023-04-10 16:10 UTC, jaroslawtt commented on frontend/src/pages/sites/sites.tsx
> +              <h2>{projectName}</h2>
should I avoid optional chaining operator here?

2023-04-10 16:55 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +              <h2>{projectName}</h2>
yes. because you should be 100% sure that there is  project
you can use cast type `(project as Type).name`

2023-04-11 07:35 UTC, what1s1ove requested changes

2023-04-11 07:35 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +      void Promise.all([
```suggestion
```
do not need this one

2023-04-11 08:34 UTC, what1s1ove approved these changes

2023-04-11 08:34 UTC, merged