sl-160: Add exit button from site
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #262
Opened 2023-04-10 14:20 UTC by jaroslawtt

https://user-images.githubusercontent.com/87016333/230919839-a12c21ed-92e2-42f8-92b7-7231bd665e99.mp4

2023-04-10 15:34 UTC, what1s1ove requested changes
it should be fixed button (always be on the screen)
you don't to fetch a current site. Label of this button should be "Back to all sites"

2023-04-10 16:15 UTC, jaroslawtt commented
> it should be fixed button (always be on the screen) you don't to fetch a current site. Label of this button should be "Back to all sites"

How I can get project id our site is associated with?

2023-04-10 16:56 UTC, what1s1ove commented
> > it should be fixed button (always be on the screen) you don't to fetch a current site. Label of this button should be "Back to all sites"
> 
> How I can get project id our site is associated with? As our path consist of "/projects/:projectId/sites", so to return back I ought to possess this id.

agreed. let's do it this way

2023-04-10 16:58 UTC, what1s1ove requested changes

2023-04-10 16:58 UTC, what1s1ove commented on frontend/src/packages/projects/projects-api.ts
> +  public async getProject(parameters: {
```suggestion
  public async getById(parameters: {
```

2023-04-10 16:58 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +          void dispatch(
call 2 action in parallel 
(sections and site)

2023-04-11 06:22 UTC, jaroslawtt commented
https://user-images.githubusercontent.com/87016333/231073339-a94b9b2d-fa1f-4be5-aa00-dc372f5c85d4.mp4

2023-04-11 08:18 UTC, what1s1ove requested changes

2023-04-11 08:18 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +import { type ProjectGetAllItemResponseDto } from '~/packages/projects/libs/types/types.js';
```suggestion
import { type ProjectGetAllItemResponseDto } from '~/packages/projects/projects.js';
```

2023-04-11 08:36 UTC, what1s1ove approved these changes

2023-04-11 08:36 UTC, merged