sl-259: The new project should displayed first
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #285
Opened 2023-04-11 16:57 UTC by Izdormu

i dont know if it good idea,to solve this problem like this
Also second way in this solution is reverse projects only in render,but again ,maybe this decision is bad in general
<div className={styles['cards-wrapper']}>
  {projects.slice().reverse().map((card) => (
    <ProjectCard
      key={card.id}
      project={card}
      onEdit={handleProjectEdit}
    />
  ))}
</div>

2023-04-11 16:59 UTC, andanf-e requested changes
Just add ordering by createdAt at the backend side

2023-04-12 09:29 UTC, andanf-e commented on backend/src/packages/projects/project.repository.ts
> +      .orderBy('created_at', 'desc')
Create a enum for sorting order

2023-04-13 08:22 UTC, what1s1ove requested changes

2023-04-13 08:22 UTC, what1s1ove commented on backend/src/libs/packages/database/libs/enums/database-sort-direction.enum.ts
> +const DatabaseSortDirection = {
move it to the shared folder

2023-04-13 12:00 UTC, what1s1ove requested changes

2023-04-13 12:00 UTC, what1s1ove commented on shared/src/packages/projects/libs/enums/projects-sort-direction.enum.ts
> +} as const;
```suggestion
const SortDirection = {
  DESCENDING: 'desc',
} as const;
```
it is a common enum

2023-04-13 12:32 UTC, what1s1ove requested changes

2023-04-13 12:32 UTC, what1s1ove commented on backend/src/packages/projects/libs/enums/enums.ts
> +  SortDirection,
```suggestion
```
it should be imported in the common enums

2023-04-14 08:55 UTC, what1s1ove approved these changes

2023-04-14 08:55 UTC, merged