sl-297: Fix pagination styles (my sites)
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #315
Opened 2023-04-12 17:09 UTC by Alexandr-mas

![image](https://user-images.githubusercontent.com/84984785/231531794-f6f03ed3-4b81-47b3-8497-a355ad2a265d.png)

2023-04-13 09:50 UTC, what1s1ove requested changes

2023-04-13 09:50 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +                <div>
```suggestion
              <div className={styles['button-wrapper']}>
```
remove useless wrappers

2023-04-13 17:43 UTC, Izdormu approved these changes

2023-04-14 07:35 UTC, what1s1ove approved these changes

2023-04-14 07:35 UTC, merged