sl-20: Sites GET / endpoint
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #38
Opened 2023-03-15 17:59 UTC by dimapopovych

![image](https://user-images.githubusercontent.com/100519494/225400810-9db73bbd-a87e-430c-bb31-08dcdb6f875b.png)

2023-03-15 18:04 UTC, dimapopovych commented
I'm not sure if this endpoint should return createdAt and updatedAt or not

2023-03-15 19:02 UTC, bohdan-degtiar approved these changes

2023-03-16 06:58 UTC, Alexandr-mas approved these changes

2023-03-16 08:06 UTC, andanf-e commented on backend/src/db/migrations/20230315143040_add_sites_table.ts
> +const COLUMN_NAME = {
B12
```suggestion
const ColumnName = {
```

2023-03-16 08:06 UTC, andanf-e commented on backend/src/packages/sites/site.controller.ts
> +
Check how to declare swagger route description

2023-03-16 08:06 UTC, andanf-e commented on backend/src/packages/sites/site.entity.ts
> +  }) {
Let's move it to type as it's duplicating in several places
`upd` looks like you've already declared such type

2023-03-16 08:12 UTC, what1s1ove requested changes
let's in this task also add `create` functionality

2023-03-16 08:20 UTC, dimapopovych commented
> let's in this task also add `create` functionality

Is it about only entity create method or I should implement another POST endpoint?

2023-03-16 08:24 UTC, what1s1ove commented
> > let's in this task also add `create` functionality
> 
> Is it about only entity create method or I should implement another POST endpoint?

all create functionality

2023-03-16 13:46 UTC, dimapopovych commented
![post response](https://user-images.githubusercontent.com/100519494/225636552-beb0e8e1-d63d-436a-903c-f7a84e512b23.png)
![response](https://user-images.githubusercontent.com/100519494/225637307-dc9520eb-4f1f-47f8-a540-3e1b64e757a7.png)

2023-03-16 16:18 UTC, what1s1ove requested changes

2023-03-16 16:18 UTC, what1s1ove commented on backend/src/packages/sites/site.controller.ts
> +  private async create(
add swagger

2023-03-16 16:23 UTC, andanf-e commented on backend/src/packages/sites/site.controller.ts
> +  private async create(
\* separate comment for separate route (split general one)

2023-03-16 21:14 UTC, andanf-e approved these changes

2023-03-17 08:33 UTC, what1s1ove approved these changes

2023-03-17 08:33 UTC, merged