sl-52: sites page
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #61
Opened 2023-03-23 09:57 UTC by Alyona-Pisotska

![photo_2023-03-23 11 56 29](https://user-images.githubusercontent.com/102159736/227167731-e388ff53-6f86-4ab2-b1a8-d5ff29d91b28.jpeg)
![photo_2023-03-23 11 56 37](https://user-images.githubusercontent.com/102159736/227167743-2417ba13-8b64-4694-a4a3-8861c645ff5b.jpeg)

2023-03-23 09:59 UTC, what1s1ove commented
merge `development` into your branch

2023-03-23 13:58 UTC, dimapopovych commented on frontend/src/pages/sites/components/site-card/site-card.tsx
> +import img from '../../../../assets/img/test.jpg';
import

2023-03-23 13:58 UTC, dimapopovych commented on frontend/src/libs/components/components.ts
> +export { Navigate, Outlet as RouterOutlet, useParams } from 'react-router-dom';
useParams should be re-exported from hooks.ts

2023-03-23 13:58 UTC, dimapopovych commented on frontend/src/pages/sites/sites.tsx
> +    // replace with user from store
```suggestion
    // replace with user from store
```

2023-03-23 13:58 UTC, dimapopovych commented on frontend/src/slices/sites/actions.ts
> +  return sitesApi.getProjectSites(payload.projectId);
await?

2023-03-23 13:58 UTC, dimapopovych commented on frontend/src/slices/sites/sites.slice.ts
> +  sites: SiteGetAllResponseDto | null;
```suggestion
  sites: SiteGetAllItemResponseDto[];
```

2023-03-23 13:58 UTC, dimapopovych commented on frontend/src/slices/sites/sites.slice.ts
> +  sites: null,
```suggestion
  sites: [];
```

2023-03-23 14:47 UTC, andanf-e requested changes

2023-03-23 14:47 UTC, andanf-e commented on backend/src/db/migrations/20230321180534_add_project_id_to_sites_table.ts
> +  return knex.schema.table(TABLE_NAME, (table) => {
```suggestion
  return knex.schema.alterTable(TABLE_NAME, (table) => {
```

2023-03-23 14:47 UTC, andanf-e commented on frontend/src/pages/sites/sites.tsx
> +};
Get user from store
```suggestion

```

2023-03-23 14:52 UTC, what1s1ove requested changes

2023-03-23 14:52 UTC, what1s1ove commented on shared/src/packages/sites/libs/validation-schemas/site-create.validation-schema.ts
> +  projectId: joi.number().required(),
```suggestion
```
we should add it on the backend

2023-03-23 14:52 UTC, what1s1ove commented on shared/src/packages/sites/libs/validation-schemas/site-get-by-project.validation-schema.ts
> +const siteGetByProject = joi.object<SiteGetByProjectRequestDtoType, true>({
```suggestion
const siteGetByProjectParams = joi.object<SiteGetByProjectRequestDtoType, true>({
```
don't forget about file name

2023-03-23 14:52 UTC, what1s1ove commented on shared/src/packages/sites/libs/types/site-get-by-project-request-dto.type.ts
> +type SiteGetByProjectRequestDtoType = {
```suggestion
type SiteGetByProjectParamsDto = {
```
don't forget about file name

2023-03-23 14:52 UTC, what1s1ove commented on shared/src/packages/sites/libs/types/site-get-all-item-response-dto.type.ts
> +  projectId: number;
```suggestion
```
should be added on the backend (not part of your task)

2023-03-23 14:52 UTC, what1s1ove commented on shared/src/packages/sites/libs/types/site-create-request-dto.type.ts
> +  projectId: number;
should be added on the backend (not part of your task)

2023-03-23 14:52 UTC, what1s1ove commented on shared/src/packages/sites/libs/enums/sites-api-path.enum.ts
> +  BY_PROJECT: '/:projectId',
```suggestion
  $PROJECT_ID: '/:projectId',
```
`$` for params

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/slices/sites/actions.ts
> +const getSites = createAsyncThunk<
```suggestion
const getSitesByProject = createAsyncThunk<
```

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/pages/sites/sites.tsx
> +  }
```suggestion
```
don't add this check for now

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/pages/my-projects/components/project-card/project-card.tsx
> +          to={`${ProjectsDetailsRoute.root}/${id}${ProjectsDetailsRoute.sites}`}
use `configurateString` helper for it

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/packages/sites/sites-api.ts
> +  public async getProjectSites(
```suggestion
  public async getByProectId(
```

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/libs/enums/app-route.enum.ts
> +};
```suggestion
```
descibe all in AppRoute

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/libs/enums/app-route.enum.ts
> +  SITES: `${ProjectsDetailsRoute.root}${ProjectsDetailsRoute.$id}${ProjectsDetailsRoute.sites}`,
```suggestion
  PROJECTS: '/projects',
  PROJECTS_$PROJECT_ID_SITES: '/projects/:projectId/sites'
```

2023-03-23 14:52 UTC, what1s1ove commented on frontend/src/assets/img/test.jpg
site-mock-image

2023-03-23 14:52 UTC, what1s1ove commented on backend/src/packages/sites/site.service.ts
> +  public async findByProject(
```suggestion
  public async findByProjectId(
```

2023-03-23 14:52 UTC, what1s1ove commented on backend/src/packages/sites/site.repository.ts
> +  public async findByProject(projectId: number): Promise<SiteEntity[]> {
```suggestion
  public async findByProjectId(projectId: number): Promise<SiteEntity[]> {
```

2023-03-23 14:52 UTC, what1s1ove commented on backend/src/packages/sites/site.controller.ts
> +  private async findByProject(
```suggestion
  private async findByProjectId(
```

2023-03-23 15:02 UTC, andanf-e commented on frontend/src/assets/css/variables.scss
> +  --card-gap: 20px;
That's nice to have reused things be moved to commons, but I believe `variables` should contain only global dependencies for styles -- so let's have this values declared locally for needed styles
```suggestion

```

2023-03-23 20:11 UTC, Alyona-Pisotska commented on frontend/src/pages/my-projects/components/project-card/project-card.tsx
> +          to={`${ProjectsDetailsRoute.root}/${id}${ProjectsDetailsRoute.sites}`}
@what1s1ove  I did it. But I have Type problem with the Link component. Property "to" of Link component has AppRoute type:
`type Properties = {
  to: ValueOf<typeof AppRoute>;
  children: React.ReactNode;
};`

But configureString returns just string type. So maybe I need to use the NavLink component or create a new Link component that has the property "to" with string type or something else ...

2023-03-24 22:29 UTC, andanf-e commented on .github/ISSUE_TEMPLATE/bug-report.md
should not be removed

2023-03-24 22:29 UTC, andanf-e commented on .ls-lint.yml
> -  .github/ISSUE_TEMPLATE:
turn it back

2023-03-24 22:29 UTC, andanf-e commented on backend/src/packages/sites/site.repository.ts
> +      .where('project_id', projectId)
Within the snakeCaseMapper we may define keys in non-snake_case(snakeCase) for not a raw queries

2023-03-24 22:29 UTC, andanf-e commented on frontend/src/pages/sites/sites.tsx
> +      <Header user={user} pageName={PageName.MY_SITES} />
Not sure if we should have header in pages other than root page

2023-03-25 09:26 UTC, andanf-e commented on frontend/src/pages/sites/sites.tsx
> +      void dispatch(sitesActions.getSitesByProject({ projectId: +projectId }));
```suggestion
      void dispatch(sitesActions.getSitesByProject({ projectId: Number(projectId) }));
```

2023-03-25 09:26 UTC, andanf-e commented on frontend/src/pages/sites/sites.tsx
> +  }));
```suggestion
  const { sites } = useAppSelector(({ sites }) => ({
    sites: sites.sites,
  }));
```

2023-03-25 10:43 UTC, what1s1ove requested changes

2023-03-25 10:43 UTC, what1s1ove commented on frontend/src/pages/my-projects/components/project-card/project-card.tsx
> +  id: number;
```suggestion
  project: Type
```
pass a full project to props

2023-03-25 10:43 UTC, what1s1ove commented on frontend/src/pages/sites/components/site-card/site-card.tsx
> +  siteName: string;
```suggestion
  site: Type
```
pass a full project to props

2023-03-25 10:43 UTC, what1s1ove commented on shared/src/packages/sites/libs/enums/sites-api-path.enum.ts
> +  $PROJECT_ID: '/:projectId',
```suggestion
```
the route should be `/projects/:projectId/sites` and it's a part of the `ProjectsApiPath `

2023-03-26 08:10 UTC, what1s1ove approved these changes

2023-03-26 08:49 UTC, andanf-e approved these changes

2023-03-26 08:53 UTC, merged