sl-83: Fix error display sign-up validation on frontend
BinaryStudioAcademy/bsa-winter-2022-2023-simpleland pull request #84
Opened 2023-03-25 16:51 UTC by kuslosolodka

![email_error_display](https://user-images.githubusercontent.com/97099358/227730744-1dba001f-8d44-48a1-b760-b669634470bb.png)

2023-03-25 16:52 UTC, andanf-e approved these changes

2023-03-25 17:00 UTC, what1s1ove requested changes

2023-03-25 17:00 UTC, what1s1ove commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +        noValidate
```suggestion
```
let' use `type="text"` and `inputmode="email"` instead

2023-03-25 17:15 UTC, what1s1ove requested changes

2023-03-25 17:15 UTC, what1s1ove commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +        inputMode="email"
```suggestion
```
provide it for the specific input. not for the full form

2023-03-26 06:42 UTC, andanf-e approved these changes

2023-03-26 07:15 UTC, what1s1ove approved these changes

2023-03-26 07:15 UTC, merged